### ISSUE TITLE
Tool displays a blank page / crashes on Internet Explorer 11

### ISSUE THREAD

**Issue by ghost** [dolbyio-samples/comms-sdk-web-call-tester#13]
**Describe the bug**

This tool doesn't work on Internet Explorer 11. It just displays a blank page. If I open the developer console, there seems to be an error (please refer to screenshots). 

In the IE11 console it reports **"MediaStream is undefined"** when we generate a bundle file using **yarn run build**

**Expected Behaviour**

The tool should be able to test the browser on Internet Explorer 11 or atleast should not crash.

**Steps to Reproduce the Problem**

  1. yarn install
  2. yarn start
  3. Run the project and go to the web page http://localhost:8081.

**Minimalistic code (recommended)**
I have cloned the repo directly.

**Specifications**

  - Device: Desktop
  - OS: Windows
  - Browser Version: 11.765.17134.0

  - Version:
    - _for each libraries : name -> version_
    - voxeet-web-sdk: ^3.0.0
    - bowser: ^2.11.0
    - node: v12.18.2
    - npm version: 6.4.1
  - Hardware:
    - _list of each specific hardware element on the system_
    -  Default - Microphone (Realtek High Definition Audio(SST))
    - Inbuilt webcam
   - Screenshots
   
**IE 11 Error**
   ![IE 11 Error](https://user-images.githubusercontent.com/46995428/103214255-f7895900-4935-11eb-8931-90a5a9a4ab06.png)

   
**Error in console when run after generating bundle file on IE11**
![Error in console when run after generating bundle file on IE11](https://user-images.githubusercontent.com/46995428/103214122-a1b4b100-4935-11eb-9860-b8defd0781bc.png)

  
**IE 11 Version details**   
![IE 11 Version details](https://user-images.githubusercontent.com/46995428/103213832-db38ec80-4934-11eb-873d-371930824865.png)

**Working perfectly on Chrome**
![Working perfectly on Chrome](https://user-images.githubusercontent.com/46995428/103213850-e8ee7200-4934-11eb-8bab-fbc6e2d75c68.png)

**Comment by ghost** [comment]
@Energizz any update on this?

**Comment by Energizz** [comment]
You will find the list of supported web browsers on this web page https://dolby.io/developers/interactivity-apis/client-sdk/articles/supported-client-platforms#web-sdk (the voxeet-sdk-web-tool is using the Web SDK)
