### ISSUE TITLE
localstats object changed in sdkv2.3 - no longer working with this tool

### ISSUE THREAD

**Issue by jchang0419** [dolbyio-samples/comms-sdk-web-call-tester#4]
**Describe the bug**

no data shows on audio/video graphs, because stat[0].stats object is undefined when updating to sdk v2.3. It changed from array to map

**Steps to Reproduce the Problem**

run latest version of the app with voxeet web sdk v2.3.1.

**Minimalistic code (recommended)**

https://github.com/voxeet/voxeet-sdk-web-tool/blob/master/src/components/VoxeetConference.js#L313

**Comment by FabienLavocat** [comment]
This issue has been fixed
