### ISSUE TITLE
broken url from documentation website to this repo

### ISSUE THREAD

**Issue by alpalex** [dolbyio-samples/comms-sdk-web-call-tester#42]
**Describe the bug**

ALL of the urls on [https://docs.dolby.io/communications-apis/docs/](this page) under the section `Project Sample Apps` are broken. It seems to me as if the [https://dolby.io/project-gallery/](Project Gallery) page has been undergoing a big change and all of the old urls (for all of the sdks) don't work any more. Frustrating...

![image](https://github.com/dolbyio-samples/comms-sdk-web-call-tester/assets/143097973/24aec986-a7ac-4116-93fd-870488aaf42f)

**Comment by FabienLavocat** [comment]
Thanks @alpalex for reporting this, we're looking at it.

**Comment by FabienLavocat** [comment]
We've temporarily removed the links, all of our sample apps are on [GitHub](https://github.com/dolbyio-samples).
